"use client"

import { ExternalLink } from "lucide-react"
import { openExternalLink } from "@/lib/external-links"

export function PiggyAI() {
  return (
    <div className="space-y-4">
      <div className="flex flex-col items-center justify-center space-y-4 py-2">
        {/* Заголовок PIGGY DEFAI */}
        <h1 className="text-2xl font-extrabold text-center text-[#fd0c96] tracking-wider">PIGGY DEFAI</h1>

        {/* Подзаголовок */}
        <p className="text-center text-white text-sm whitespace-nowrap">V1.0 AGENT NOW AVAILABLE ON TELEGRAM</p>

        {/* Кнопка USE THE PIGGY DEFAI BOT */}
        <button
          onClick={() => openExternalLink("https://t.me/PiggyAgent_Bot")}
          className="bg-[#fd0c96] hover:bg-[#fd0c96]/80 text-white font-bold w-full px-4 py-2 rounded-md flex items-center justify-center"
        >
          USE THE PIGGY DEFAI BOT
          <ExternalLink className="ml-2 h-4 w-4" />
        </button>

        {/* Описание */}
        <p className="text-center text-white text-sm px-4 mt-2">
          Meet Piggy — your AI-powered, Telegram-based financial agent that grades your portfolio, optimizes your yield,
          and will even execute transactions so you can maximize earnings with zero hassle
        </p>

        {/* Блоки текста - уменьшенный размер */}
        <div className="space-y-4 mt-3">
          <p className="text-center text-white text-xs font-bold px-4">
            PIGGY UTILIZES SUPERFORM'S AGENT-OPTIMIZED V2 PROTOCOL TO ANALYZE EVERY ASSET ON EVERY CHAIN & ALL THE YIELD
            BEING GENERATED BY THESE ASSETS
          </p>

          <p className="text-center text-white text-xs font-bold px-4">THE FUTURE OF AI & CRYPTO LIVES WITH PIGGY</p>
        </div>

        {/* Кнопка OINK IT */}
        <button
          onClick={() =>
            openExternalLink("https://mirror.xyz/basedpiggy.eth/SnvKX-LTceDZaEXO_-LWYCodGK68ftUIdSnnzy5B2HU")
          }
          className="bg-[#fd0c96] hover:bg-[#fd0c96]/80 text-white font-bold w-full px-4 py-2 rounded-md flex items-center justify-center mt-2"
        >
          OINK IT
          <ExternalLink className="ml-2 h-4 w-4" />
        </button>

        {/* Кнопка Token Information */}
        <button
          onClick={() => openExternalLink("https://piggy.vision")}
          className="border-[#fd0c96] text-[#fd0c96] hover:bg-[#fd0c96]/10 font-bold w-full px-4 py-2 rounded-md border flex items-center justify-center"
        >
          Token Information
          <ExternalLink className="ml-2 h-4 w-4" />
        </button>

        {/* Кнопка MINT OINKDENTITY с HTTPS ссылкой */}
        <button
          onClick={() => openExternalLink("https://id.piggyworld.xyz")}
          className="bg-[#fd0c96] hover:bg-[#fd0c96]/80 text-white font-bold w-full px-4 py-2 rounded-md flex items-center justify-center"
        >
          MINT OINKDENTITY
          <ExternalLink className="ml-2 h-4 w-4" />
        </button>
      </div>
    </div>
  )
}
